name: Trigger auto deployment for deploy-aca-demo

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/deploy-aca-demo-AutoDeployTrigger-9fdd9291-2456-4419-9160-0994ec28a531.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.DEPLOYACADEMO_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: ca99bd887143acr.azurecr.io
          registryUsername: ${{ secrets.DEPLOYACADEMO_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.DEPLOYACADEMO_REGISTRY_PASSWORD }}
          containerAppName: deploy-aca-demo
          resourceGroup: rg-deploy-aca-demo
          imageToBuild: ca99bd887143acr.azurecr.io/deploy-aca-demo:${{ github.sha }}
          
            

     

